"""github_intel initial schema

Revision ID: a877843016fd
Revises: 
Create Date: 2026-07-01 08:17:18.634058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a877843016fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gh_capabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='github_intel'
    )
    op.create_index(op.f('ix_github_intel_gh_capabilities_slug'), 'gh_capabilities', ['slug'], unique=True, schema='github_intel')
    op.create_table('gh_engineering_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='github_intel'
    )
    op.create_index(op.f('ix_github_intel_gh_engineering_features_slug'), 'gh_engineering_features', ['slug'], unique=True, schema='github_intel')
    op.create_table('gh_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('github_username', sa.String(length=255), nullable=False),
    sa.Column('github_url', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='github_intel'
    )
    op.create_index(op.f('ix_github_intel_gh_profiles_github_username'), 'gh_profiles', ['github_username'], unique=True, schema='github_intel')
    op.create_table('gh_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('aliases_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='github_intel'
    )
    op.create_index(op.f('ix_github_intel_gh_skills_name'), 'gh_skills', ['name'], unique=True, schema='github_intel')
    op.create_table('gh_feature_capability_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['github_intel.gh_capabilities.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['github_intel.gh_engineering_features.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='github_intel'
    )
    op.create_index(op.f('ix_github_intel_gh_feature_capability_edges_capability_id'), 'gh_feature_capability_edges', ['capability_id'], unique=False, schema='github_intel')
    op.create_index(op.f('ix_github_intel_gh_feature_capability_edges_feature_id'), 'gh_feature_capability_edges', ['feature_id'], unique=False, schema='github_intel')
    op.create_table('gh_repositories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('topics_json', sa.Text(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('size_kb', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('clone_url', sa.String(length=512), nullable=False),
    sa.Column('default_branch', sa.String(length=128), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('commit_activity', sa.Float(), nullable=False),
    sa.Column('analyzed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['github_intel.gh_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='github_intel'
    )
    op.create_index(op.f('ix_github_intel_gh_repositories_profile_id'), 'gh_repositories', ['profile_id'], unique=False, schema='github_intel')
    op.create_table('gh_skill_capability_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['github_intel.gh_capabilities.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['github_intel.gh_skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='github_intel'
    )
    op.create_index(op.f('ix_github_intel_gh_skill_capability_edges_capability_id'), 'gh_skill_capability_edges', ['capability_id'], unique=False, schema='github_intel')
    op.create_index(op.f('ix_github_intel_gh_skill_capability_edges_skill_id'), 'gh_skill_capability_edges', ['skill_id'], unique=False, schema='github_intel')
    op.create_table('gh_repository_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('architecture_features_json', sa.Text(), nullable=False),
    sa.Column('dependencies_json', sa.Text(), nullable=False),
    sa.Column('architecture_layers_json', sa.Text(), nullable=False),
    sa.Column('patterns_json', sa.Text(), nullable=False),
    sa.Column('features_json', sa.Text(), nullable=False),
    sa.Column('git_history_json', sa.Text(), nullable=False),
    sa.Column('complexity_json', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['github_intel.gh_repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='github_intel'
    )
    op.create_index(op.f('ix_github_intel_gh_repository_analyses_repository_id'), 'gh_repository_analyses', ['repository_id'], unique=True, schema='github_intel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_intel_gh_repository_analyses_repository_id'), table_name='gh_repository_analyses', schema='github_intel')
    op.drop_table('gh_repository_analyses', schema='github_intel')
    op.drop_index(op.f('ix_github_intel_gh_skill_capability_edges_skill_id'), table_name='gh_skill_capability_edges', schema='github_intel')
    op.drop_index(op.f('ix_github_intel_gh_skill_capability_edges_capability_id'), table_name='gh_skill_capability_edges', schema='github_intel')
    op.drop_table('gh_skill_capability_edges', schema='github_intel')
    op.drop_index(op.f('ix_github_intel_gh_repositories_profile_id'), table_name='gh_repositories', schema='github_intel')
    op.drop_table('gh_repositories', schema='github_intel')
    op.drop_index(op.f('ix_github_intel_gh_feature_capability_edges_feature_id'), table_name='gh_feature_capability_edges', schema='github_intel')
    op.drop_index(op.f('ix_github_intel_gh_feature_capability_edges_capability_id'), table_name='gh_feature_capability_edges', schema='github_intel')
    op.drop_table('gh_feature_capability_edges', schema='github_intel')
    op.drop_index(op.f('ix_github_intel_gh_skills_name'), table_name='gh_skills', schema='github_intel')
    op.drop_table('gh_skills', schema='github_intel')
    op.drop_index(op.f('ix_github_intel_gh_profiles_github_username'), table_name='gh_profiles', schema='github_intel')
    op.drop_table('gh_profiles', schema='github_intel')
    op.drop_index(op.f('ix_github_intel_gh_engineering_features_slug'), table_name='gh_engineering_features', schema='github_intel')
    op.drop_table('gh_engineering_features', schema='github_intel')
    op.drop_index(op.f('ix_github_intel_gh_capabilities_slug'), table_name='gh_capabilities', schema='github_intel')
    op.drop_table('gh_capabilities', schema='github_intel')
    # ### end Alembic commands ###
